//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta
    {
        public int Id { get; set; }
        public string Titular { get; set; }
        public int Tipo { get; set; }
        public short Numero { get; set; }
        public double Saldo { get; set; }
        public virtual void Saca(double valorOperacao)
        {
            Saldo -= valorOperacao;
        }
        public virtual void Deposita(double valorOperacao)
        {
           Saldo += valorOperacao;
        }

    }
}
