//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poupanca : Conta
    {
        static double taxa = 0.10;
        public override void Saca(double valorOperacao)
        {
            Saldo -= valorOperacao + taxa;
        }
        public override void Deposita(double valorOperacao)
        {
            Saldo += valorOperacao;
        }
    }
}
