USE [C:\USERS\MIMDUIM\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\BANCO\BANCO\BANCODB.MDF]

CREATE TABLE CLIENTE (
    IDCLIENTE INT NOT NULL UNIQUE IDENTITY (1,1) ,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(14) NOT NULL UNIQUE,
	RG VARCHAR(10) NOT NULL UNIQUE,
	SEXO CHAR NOT NULL,
	IDADE SMALLINT NOT NULL,
	NACIONALIDADE VARCHAR(20) NOT NULL,
	PRIMARY KEY (IDCLIENTE, CPF, RG)
)
GO

CREATE TABLE CONTA (
    IDCONTA INT NOT NULL UNIQUE IDENTITY (1,1) ,
	TITULAR VARCHAR(14) NOT NULL,
	TIPO SMALLINT NOT NULL,
	NUMERO INT NOT NULL UNIQUE,
	SALDO FLOAT NOT NULL ,	
	PRIMARY KEY (IDCONTA),
	FOREIGN KEY (TITULAR)
	REFERENCES CLIENTE(CPF)
)
GO
